name: dump
description: |
  環境変数とgithubコンテキストをログに出力します。
  デバッグ用です。
inputs:
  enable-context:
    default: 'true'
    required: false
    description: コンテキストをログ出力するか
ouputs:
  dumped-date:
    value: ${{ steps.dump.outputs.dumped-date }}
    description: dump日時
runs:
  using: 'composite'
  steps:
    - run: printenv | sort
      shell: bash
    - run: echo "${CONTEXT}"
      if: ${{ inputs.enable-context == 'true' }}
      env:
        CONTEXT: ${{ toJson(github) }}
      shell: bash
    - id: current
      run: echo "date=$(date)" >> "${GITHUB_OUTPUT}"
      shell: bash