name: Contexts
on: workflow_dispatch
jobs:
  print: 
    runs-on: ubuntu-latest
    env:
      ACTOR: ${{ github.actor }}
      USERNAME: ${{ vars.USERNAME }}
      PRSSWORD: ${{ secrets.PASSWORD }}
    steps:
      - run: echo "${ACTOR}"
      - run: echo "${USERNAME}"
      - run: echo "${PRSSWORD}"
      - run: echo "${PRSSWORD:0:1} ${PRSSWORD#?}"
      