name: Literals
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep 'LITERAL_'
        env:
          LITERAL_NULL: ${{ null }}
          LITERAL_NUMBER: ${{ 12345 }}
          LITERAL_BOOLEAN: ${{ true }}
          LITERAL_STRING: ${{ 'Hello' }}
          LITERAL_OMIT_STRING: Hello