name: Matrix
on: [workflow_dispatch]
jobs:
  print:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "This is ${{ matrix.os }}"
        shell: bash