name: Naming
run-name: Run by @${{github.actor}}
on: [push]
jobs:
  print:
    name: Super Userful job
    runs-on: ubuntu-latest
    steps:
      - name: Amazing Script
        run: echo "This is a placeholder workflow to demonstrate naming conventions."
      - name: Thomas
        run: echo "fjijfiwpohjfiahfiohwapfihawpih3984930480"