name: Sequential jobs
on: [workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is job 1"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "This is job 2"
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - run: echo "This is job 3"
  job4:
    runs-on: ubuntu-latest
    needs: job3
    steps:
      - run: echo "This is job 4"