name: Share jobs data
on: [workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: set_output
        run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
    outputs:
      data: ${{ steps.set_output.outputs.data }}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "Data from job 1: ${{ needs.job1.outputs.data }}"