name: Share jobs data
on: [workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: set_output
        run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
    outputs:
      result: ${{ steps.set_output.outputs.result }}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          RESULT: ${{ needs.job1.outputs.result }}
      - run: echo "Data from job 1 ${RESULT}"